# name: Deploy to VPS

# on:
#   push:
#     branches:
#       - main  # Trigger the workflow on pushes to the 'main' branch

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       # Checkout the code from the repository
#       - name: Checkout code
#         uses: actions/checkout@v2

#       # Set up SSH to connect to your VPS using the private SSH key stored in GitHub secrets
#       - name: Set up SSH
#         uses: webfactory/ssh-agent@v0.5.3
#         with:
#           ssh-private-key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}

#       # Deploy to VPS and run necessary commands to update dependencies and restart the server
#       - name: Deploy to VPS
#         run: |
#           ssh -o StrictHostKeyChecking=no root@145.223.18.97 "
#             cd /var/www/Solar-DL-Backend-2.0 && \
#             git pull origin main && \
#             npm install --production && \
#             pm2 restart all
#           "

name: Deploy to VPS

on:
  push:
    branches:
      - main # Trigger the workflow on pushes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up SSH to connect to the VPS using the private SSH key stored in GitHub secrets
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}

      # Step 3: Find all .env files, bundle them into a tar archive, and upload to VPS
      - name: Upload all .env files to VPS
        run: |
          # Compress all .env files into a single archive (handle spaces properly)
          find . -name ".env" -print0 | tar --null -cvf env_files.tar --files-from=-

          # Upload the tar archive to the server
          scp -o StrictHostKeyChecking=no env_files.tar root@145.223.18.97:/var/www/Solar-DL-Backend-2.0/

          # Extract the .env files on the server and clean up the archive
          ssh -o StrictHostKeyChecking=no root@145.223.18.97 "
            cd /var/www/Solar-DL-Backend-2.0 && \
            tar -xvf env_files.tar && \
            rm env_files.tar
          "

      # Step 4: Deploy to VPS and run necessary commands
      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no root@145.223.18.97 "
            cd /var/www/Solar-DL-Backend-2.0 && \
            git pull origin main && \
            npm install --production && \
            pm2 restart all
          "
